name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Tests
      run: |
        yarn install
        yarn test
    - name: Audit
      run: |
        yarn install
        yarn audit
    - name: Build
      env: 
        REACT_APP_API_TMDB: ${{ secrets.REACT_APP_API_TMDB }}
      run: |
        yarn install
        yarn build
    - name: Firebase Deploy
      run: |
        sudo npm install -g firebase-tools
        firebase use movieapp-ts --token ${{ secrets.FIREBASE_TOKEN }}
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
